### PR TITLE
fixed some citations in the text

### PR DESCRIPTION
**Pull request by gkrahmann**

### CODE REVIEW

**Comment by soerenthomsen** [comment]
There are again some old commits if i see it correctly but no conflicts. I will merge it.

**Review by soerenthomsen — APPROVED** [review]

**Comment by gkrahmann** [comment]
most of these seem to come from me opening a branch in my fork and they all show up in the list
they are however totally meaningless for the comparison with the main as for the pull request
only my main was compared with the main main
no idea how to get rid of this commits...
so this should be ok

**Comment by soerenthomsen** [comment]
@jbusecke do you have any idea why always old commits show up?

**Comment by gkrahmann** [comment]
This is what my fork shows

This branch is 8 commits ahead of OceanGlidersCommunity:main. 

even though these are this PR
So my commits do not dissappear after a PR.
I guess I am missing one of the 10 buttons I have to push for a PR.

**Pull request merged**
