### PR TITLE
dummy pull request with no changes

### PR DESCRIPTION
**Pull request by gkrahmann**
merge this one 
and I might get rid of my old commits
no file has changed

if this works, then the problem was that I used the wrong button to create a PR

### CODE REVIEW

**Comment by soerenthomsen** [comment]
I merged. Indeed no file is changed but still all the commits show up.

**Comment by gkrahmann** [comment]
hmmm
after I merged it now shows
This branch is 9 commits ahead of OceanGlidersCommunity:main.

**Comment by soerenthomsen** [comment]
@jbusecke might be able to help with this next week.

**Comment by gkrahmann** [comment]
Capture
Here is a picture of the problem.
I just did a fetch and merge and that is the merging of the blue line with black line at the right end.
The black dots are my (local) commits yesterday, for which I created a pull request (the blue line is asked to be pulled).
Interestingly the blue line branches out before the PR (blue dot) is done. It has (!) all the changes from the commits 
from the black line in its PR but does not have these commits. That's why in the next round all these commits are submitted again. So how do I get my PR to branch off later ?
I must be missing something...
When I do my updates (editing files) to my personal main (without a personal PR), do I have to push anything else for them to be merged to my main ?

**Comment by gkrahmann** [comment]
it reads a bit like this
https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch
but I do not understand git-speak well enough...

**Pull request merged**
