### PR TITLE
fixed typos in bib, added some more references

### PR DESCRIPTION
**Pull request by gkrahmann**
There is apparently a problem with the bib files so that it can not automatically merge. No idea what that is.

### CODE REVIEW

**Comment by soerenthomsen** [comment]
Hi @gkrahmann, 

I don't know why so many old commits are sent again in the new pull-requests.
See under "commits".

I suggest to try to create batches on the main document and see whether this works better? Or rebase your fork?

**Comment by gkrahmann** [comment]
I have already rebased, but I must be doing something wrong as all old internal commit are always sent again.
Is there a complete workflow which buttons I have to push at which time ?

**Comment by soerenthomsen** [comment]
Now there are also 6 conflicts, cannot merge this like this.

**Comment by gkrahmann** [comment]
I will copy the bib file to my computer and rebase and mod again and repush
So you can decline the push or how was that done ?

**Comment by gkrahmann** [comment]
all other changes are small

**Comment by soerenthomsen** [comment]
Ok I will close this pull-request without merging. You can also remove your fork and rebase after.

Another option is to just do the edits directly on the main via "branches" but always do pull-requests in that case.

**Pull request closed without merging**
