### PR TITLE
second seaexplorer image with diff config

### PR DESCRIPTION
**Pull request by gkrahmann**
there is this :::{figure-md} slocum_suna  now three times before each of the different images. What does this do and should the be modified for the non-slocum images ?

### CODE REVIEW

**Comment by soerenthomsen** [comment]
the "slocum_suna" is the figure tag, it should be specific for each figure to cite it in the text. 
:::{figure-md} ...  stays always...

You can check here: https://github.com/OceanGlidersCommunity/Oxygen_SOP/blob/main/sections/oxygen_mission_execution.md

**Comment by soerenthomsen** [comment]
Do the labels make sense?

**Review by soerenthomsen — APPROVED** [review]

**Comment by gkrahmann** [comment]
do I have to do something ?
Merge ?

**Comment by gkrahmann** [comment]
labels make sense

**Comment by soerenthomsen** [comment]
I merged. Please also adapt the "permissions.md" file in the images folder

**Pull request merged**
